# Exploratory Data Analysis

In [1]:
import pandas as pd
import numpy as np
from logistic_regression import LogisticRegressionScratch
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv('../data/Churn_Modelling.csv')

In [3]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  str
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  str
 5   Gender           10000 non-null  str
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), str(3)
memory usage: 1.1 MB

In [5]:
df.isna().sum().sort_values()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [6]:
df[df.duplicated()]

Empty DataFrame
Columns: [RowNumber, CustomerId, Surname, CreditScore, Geography, Gender, Age, Tenure, Balance, NumOfProducts, HasCrCard, IsActiveMember, EstimatedSalary, Exited]
Index: []

In [7]:
df.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [8]:
df[['Gender', 'Geography']].nunique()

Gender       2
Geography    3
dtype: int64

## One-hot encoding

In [9]:
from sklearn.preprocessing import LabelEncoder, StandardScaler

# Just labeling gender because its just two possible values
label_encoder = LabelEncoder()
df['Gender'] = label_encoder.fit_transform(df['Gender'])

# Getting dummies from column Geography
df = pd.get_dummies(df, columns=['Geography'], drop_first=True)
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain
0,1,15634602,Hargrave,619,0,42,2,0.00,1,1,1,101348.88,1,False,False
1,2,15647311,Hill,608,0,41,1,83807.86,1,0,1,112542.58,0,False,True
2,3,15619304,Onio,502,0,42,8,159660.80,3,1,0,113931.57,1,False,False
3,4,15701354,Boni,699,0,39,1,0.00,2,0,0,93826.63,0,False,False
4,5,15737888,Mitchell,850,0,43,2,125510.82,1,1,1,79084.10,0,False,True

## Feature Selection

In [10]:
features = ['CreditScore', 'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary', 'Geography_Germany', 'Geography_Spain']

X = df[features]
y = df['Exited']

In [11]:
print(f'frequency of 1: {y.mean()}\nfrequency of 0: {1 - y.mean()}')

frequency of 1: 0.2037
frequency of 0: 0.7963

### *The result above shows that about 80% of the clients don't churn, thus accuracy can be a misleading metric.*

## Splitting dataset and feature scalling

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [13]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [14]:
[X_train.min(), X_train.max()], [X_test.min(), X_test.max()]

([np.float64(-3.1136895404483385), np.float64(5.040117203742861)],
 [np.float64(-3.1136895404483385), np.float64(4.375111058022631)])

In [15]:
X_train.shape

(8000, 11)

In [16]:
X_train.shape[0] // 5

1600

## Hyperparameter tuning with CV
*Using f2 score as metric, since accuracy can mislead and recall is important in this classification problem*

In [17]:
from sklearn.metrics import auc, precision_recall_curve

learning_rates = np.linspace(0.01, 1, 10)
scores = []
k_folds = 5
for learning_rate in learning_rates:
    pr_auc_scores = []
    for k in range(k_folds):
        kth_part_begin, kth_part_end = ((X_train.shape[0] // k_folds) * k), ((X_train.shape[0] // k_folds) * (k+1))

        X_cv_train = np.concatenate([X_train[:kth_part_begin], X_train[kth_part_end:]])
        y_cv_train = np.concatenate([y_train[:kth_part_begin], y_train[kth_part_end:]])
        
        X_cv_test = X_train[kth_part_begin : kth_part_end]
        y_cv_test = y_train[kth_part_begin : kth_part_end]

        logreg_scratch = LogisticRegressionScratch(learning_rate)
        logreg_scratch.fit(X_cv_train, y_cv_train)

        y_cv_pred = logreg_scratch.predict(X_cv_test)
        y_cv_pred_proba = logreg_scratch.predict_proba(X_cv_test)

        precision, recall, thresholds = precision_recall_curve(y_cv_test, y_cv_pred_proba)
        
        pr_auc_scores.append(auc(recall, precision))


    pr_auc_scores_mean = np.sum(pr_auc_scores) / len(pr_auc_scores)

    print(f'learning rate: {learning_rate}, pr_auc_score: {pr_auc_scores_mean}')
    scores.append(pr_auc_scores_mean)

best_hyperparam = learning_rates[scores.index(max(scores))]
print(f'best learning_rate: {best_hyperparam}')

learning rate: 0.01, pr_auc_score: 0.45680008711299147
learning rate: 0.12, pr_auc_score: 0.4640172259863807
learning rate: 0.23, pr_auc_score: 0.46401818761055297
learning rate: 0.34, pr_auc_score: 0.46401818761055297
learning rate: 0.45, pr_auc_score: 0.46401818761055297
learning rate: 0.56, pr_auc_score: 0.46401818761055297
learning rate: 0.67, pr_auc_score: 0.46401818761055297
learning rate: 0.78, pr_auc_score: 0.46401818761055297
learning rate: 0.89, pr_auc_score: 0.46401818761055297
learning rate: 1.0, pr_auc_score: 0.46401818761055297
best learning_rate: 0.23

### As we've seen before, the frequency of churn is 0.2, setting this as baseline of the pr auc score, 0.46 is a great pr auc score

## Fitting model with best learning rate

In [18]:
logreg_scratch = LogisticRegressionScratch(best_hyperparam)
logreg_scratch.fit(X_train, y_train)

## Looking results in test set and defining best threshold using f2 score, aiming to emphasize recall

In [19]:
from sklearn.metrics import confusion_matrix, classification_report, fbeta_score

thresholds = np.linspace(0.1, 0.9, 10)
f2_scores = []
for threshold in thresholds:
    y_pred_scratch = logreg_scratch.predict(X_test, threshold)
    conf_matrix_scratch = confusion_matrix(y_test, y_pred_scratch)
    class_report_scratch = classification_report(y_test, y_pred_scratch)
    f2_score_scratch = fbeta_score(y_test, y_pred_scratch, beta=2)
    f2_scores.append(f2_score_scratch)

    print(f'Results of {threshold:.2f} threshold:')
    print(f'f2_score: {f2_score_scratch:.2f}')
    print(class_report_scratch)
    print(conf_matrix_scratch)

Results of 0.10 threshold:
f2_score: 0.61
              precision    recall  f1-score   support

           0       0.94      0.36      0.53      1593
           1       0.27      0.90      0.41       407

    accuracy                           0.47      2000
   macro avg       0.60      0.63      0.47      2000
weighted avg       0.80      0.47      0.50      2000

[[ 581 1012]
 [  39  368]]
Results of 0.19 threshold:
f2_score: 0.61
              precision    recall  f1-score   support

           0       0.91      0.67      0.77      1593
           1       0.36      0.73      0.48       407

    accuracy                           0.68      2000
   macro avg       0.63      0.70      0.63      2000
weighted avg       0.80      0.68      0.71      2000

[[1068  525]
 [ 109  298]]
Results of 0.28 threshold:
f2_score: 0.53
              precision    recall  f1-score   support

           0       0.88      0.84      0.86      1593
           1       0.46      0.55      0.50       407

    accuracy                           0.78      2000
   macro avg       0.67      0.69      0.68      2000
weighted avg       0.79      0.78      0.79      2000

[[1331  262]
 [ 182  225]]
Results of 0.37 threshold:
f2_score: 0.41
              precision    recall  f1-score   support

           0       0.85      0.91      0.88      1593
           1       0.53      0.39      0.45       407

    accuracy                           0.80      2000
   macro avg       0.69      0.65      0.66      2000
weighted avg       0.79      0.80      0.79      2000

[[1450  143]
 [ 248  159]]
Results of 0.46 threshold:
f2_score: 0.27
              precision    recall  f1-score   support

           0       0.83      0.95      0.89      1593
           1       0.54      0.24      0.34       407

    accuracy                           0.80      2000
   macro avg       0.69      0.60      0.61      2000
weighted avg       0.77      0.80      0.77      2000

[[1509   84]
 [ 308   99]]
Results of 0.54 threshold:
f2_score: 0.18
              precision    recall  f1-score   support

           0       0.82      0.98      0.89      1593
           1       0.65      0.15      0.25       407

    accuracy                           0.81      2000
   macro avg       0.73      0.57      0.57      2000
weighted avg       0.78      0.81      0.76      2000

[[1559   34]
 [ 345   62]]
Results of 0.63 threshold:
f2_score: 0.09
              precision    recall  f1-score   support

           0       0.81      0.99      0.89      1593
           1       0.64      0.07      0.13       407

    accuracy                           0.80      2000
   macro avg       0.73      0.53      0.51      2000
weighted avg       0.77      0.80      0.73      2000

[[1577   16]
 [ 378   29]]
Results of 0.72 threshold:
f2_score: 0.04
              precision    recall  f1-score   support

           0       0.80      1.00      0.89      1593
           1       0.87      0.03      0.06       407

    accuracy                           0.80      2000
   macro avg       0.83      0.52      0.48      2000
weighted avg       0.81      0.80      0.72      2000

[[1591    2]
 [ 394   13]]
Results of 0.81 threshold:
f2_score: 0.01
              precision    recall  f1-score   support

           0       0.80      1.00      0.89      1593
           1       0.75      0.01      0.01       407

    accuracy                           0.80      2000
   macro avg       0.77      0.50      0.45      2000
weighted avg       0.79      0.80      0.71      2000

[[1592    1]
 [ 404    3]]
Results of 0.90 threshold:
f2_score: 0.00
              precision    recall  f1-score   support

           0       0.80      1.00      0.89      1593
           1       0.00      0.00      0.00       407

    accuracy                           0.80      2000
   macro avg       0.40      0.50      0.44      2000
weighted avg       0.63      0.80      0.71      2000

[[1593    0]
 [ 407    0]]

c:\Users\Matheus\Desktop\git_repositories\churn_predict_model\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\Matheus\Desktop\git_repositories\churn_predict_model\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\Matheus\Desktop\git_repositories\churn_predict_model\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [20]:
best_threshold = thresholds[f2_scores.index(max(f2_scores))]
print(f'Best threshold: {best_threshold}')

Best threshold: 0.1